from tkinter import *
def pr():
    sna = str(name.get())
    print(sna)
    cla = cl.get(ACTIVE)
    print(cla)
    s.set('helo')

root = Tk()
s = StringVar()
Label(root,text = '').grid(row=0,column = 0)
Label(root,text = 'Name:').grid(row=1,column = 0)
name = Entry(root,textvar=s)
Label(root,text = 'Roll No:').grid(row=2,column = 0)
roll_no = Entry(root)
Label(root,text = 'Class').grid(row=3,column = 0,rowspan=6)
cl = Listbox(root)
cl.insert(1,'FYCS')
cl.insert(2,'FYIT')
cl.insert(1,'SYCS')
cl.insert(1,'SYIT')
cl.insert(1,'TYCS')
cl.insert(1,'TYIT')
Button(root,text="hello",command=pr).grid(row=9,column=0)
# sna = name.get()
cl.grid(row=3,column=1,rowspan=6)
name.grid(row=1,column=1)
roll_no.grid(row=2,column=1)
root.mainloop()